// Code generated by protoc-gen-go.
// source: IM.Buddy.proto
// DO NOT EDIT!

package youmai

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// ==========================================================
// 联系人相关操作
// ==========================================================
type BuddyOptType int32

const (
	BuddyOptType_BUDDY_OPT_ADD BuddyOptType = 1
	BuddyOptType_BUDDY_OPT_DEL BuddyOptType = 2
)

var BuddyOptType_name = map[int32]string{
	1: "BUDDY_OPT_ADD",
	2: "BUDDY_OPT_DEL",
}
var BuddyOptType_value = map[string]int32{
	"BUDDY_OPT_ADD": 1,
	"BUDDY_OPT_DEL": 2,
}

func (x BuddyOptType) Enum() *BuddyOptType {
	p := new(BuddyOptType)
	*p = x
	return p
}
func (x BuddyOptType) String() string {
	return proto.EnumName(BuddyOptType_name, int32(x))
}
func (x *BuddyOptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BuddyOptType_value, data, "BuddyOptType")
	if err != nil {
		return err
	}
	*x = BuddyOptType(value)
	return nil
}
func (BuddyOptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// 用户头像修改请求
type IMChangeAvatarReq struct {
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	AppId            *string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	AvatarUrl        *string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl" json:"avatar_url,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMChangeAvatarReq) Reset()                    { *m = IMChangeAvatarReq{} }
func (m *IMChangeAvatarReq) String() string            { return proto.CompactTextString(m) }
func (*IMChangeAvatarReq) ProtoMessage()               {}
func (*IMChangeAvatarReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *IMChangeAvatarReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *IMChangeAvatarReq) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *IMChangeAvatarReq) GetAvatarUrl() string {
	if m != nil && m.AvatarUrl != nil {
		return *m.AvatarUrl
	}
	return ""
}

func (m *IMChangeAvatarReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 用户头像修改返回
type IMChangeAvatarRsp struct {
	// cmd id:		0x7210
	Result           *ResultCode `protobuf:"varint,1,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	UpdateTime       *uint64     `protobuf:"varint,2,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	AttachData       []byte      `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *IMChangeAvatarRsp) Reset()                    { *m = IMChangeAvatarRsp{} }
func (m *IMChangeAvatarRsp) String() string            { return proto.CompactTextString(m) }
func (*IMChangeAvatarRsp) ProtoMessage()               {}
func (*IMChangeAvatarRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *IMChangeAvatarRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

func (m *IMChangeAvatarRsp) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *IMChangeAvatarRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 个性签名修改请求
type IMChangeSignInfoReq struct {
	// cmd id:		0x7212
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	AppId            *string `protobuf:"bytes,2,opt,name=app_id,json=appId" json:"app_id,omitempty"`
	SignInfo         *string `protobuf:"bytes,3,opt,name=sign_info,json=signInfo" json:"sign_info,omitempty"`
	AttachData       []byte  `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMChangeSignInfoReq) Reset()                    { *m = IMChangeSignInfoReq{} }
func (m *IMChangeSignInfoReq) String() string            { return proto.CompactTextString(m) }
func (*IMChangeSignInfoReq) ProtoMessage()               {}
func (*IMChangeSignInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *IMChangeSignInfoReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *IMChangeSignInfoReq) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *IMChangeSignInfoReq) GetSignInfo() string {
	if m != nil && m.SignInfo != nil {
		return *m.SignInfo
	}
	return ""
}

func (m *IMChangeSignInfoReq) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 个性签名修改返回
type IMChangeSignInfoRsp struct {
	// cmd id:		0x7213
	Result           *ResultCode `protobuf:"varint,1,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	UpdateTime       *uint64     `protobuf:"varint,2,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	AttachData       []byte      `protobuf:"bytes,20,opt,name=attach_data,json=attachData" json:"attach_data,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *IMChangeSignInfoRsp) Reset()                    { *m = IMChangeSignInfoRsp{} }
func (m *IMChangeSignInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*IMChangeSignInfoRsp) ProtoMessage()               {}
func (*IMChangeSignInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *IMChangeSignInfoRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

func (m *IMChangeSignInfoRsp) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *IMChangeSignInfoRsp) GetAttachData() []byte {
	if m != nil {
		return m.AttachData
	}
	return nil
}

// 联系人操作请求
type IMOptBuddyReq struct {
	// cmd id: 0x7216
	SrcUserId        *string       `protobuf:"bytes,1,opt,name=src_user_id,json=srcUserId" json:"src_user_id,omitempty"`
	DestUserId       *string       `protobuf:"bytes,2,opt,name=dest_user_id,json=destUserId" json:"dest_user_id,omitempty"`
	OptType          *BuddyOptType `protobuf:"varint,3,opt,name=opt_type,json=optType,enum=youmai.BuddyOptType" json:"opt_type,omitempty"`
	OptRemark        *string       `protobuf:"bytes,4,opt,name=opt_remark,json=optRemark" json:"opt_remark,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *IMOptBuddyReq) Reset()                    { *m = IMOptBuddyReq{} }
func (m *IMOptBuddyReq) String() string            { return proto.CompactTextString(m) }
func (*IMOptBuddyReq) ProtoMessage()               {}
func (*IMOptBuddyReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *IMOptBuddyReq) GetSrcUserId() string {
	if m != nil && m.SrcUserId != nil {
		return *m.SrcUserId
	}
	return ""
}

func (m *IMOptBuddyReq) GetDestUserId() string {
	if m != nil && m.DestUserId != nil {
		return *m.DestUserId
	}
	return ""
}

func (m *IMOptBuddyReq) GetOptType() BuddyOptType {
	if m != nil && m.OptType != nil {
		return *m.OptType
	}
	return BuddyOptType_BUDDY_OPT_ADD
}

func (m *IMOptBuddyReq) GetOptRemark() string {
	if m != nil && m.OptRemark != nil {
		return *m.OptRemark
	}
	return ""
}

// 联系人操作结果返回
type IMOptBuddyRsp struct {
	UserId           *string       `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ResponseTime     *uint64       `protobuf:"varint,2,opt,name=response_time,json=responseTime" json:"response_time,omitempty"`
	OptType          *BuddyOptType `protobuf:"varint,3,opt,name=opt_type,json=optType,enum=youmai.BuddyOptType" json:"opt_type,omitempty"`
	Result           *int32        `protobuf:"varint,4,opt,name=result" json:"result,omitempty"`
	OptRemark        *string       `protobuf:"bytes,5,opt,name=opt_remark,json=optRemark" json:"opt_remark,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *IMOptBuddyRsp) Reset()                    { *m = IMOptBuddyRsp{} }
func (m *IMOptBuddyRsp) String() string            { return proto.CompactTextString(m) }
func (*IMOptBuddyRsp) ProtoMessage()               {}
func (*IMOptBuddyRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *IMOptBuddyRsp) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *IMOptBuddyRsp) GetResponseTime() uint64 {
	if m != nil && m.ResponseTime != nil {
		return *m.ResponseTime
	}
	return 0
}

func (m *IMOptBuddyRsp) GetOptType() BuddyOptType {
	if m != nil && m.OptType != nil {
		return *m.OptType
	}
	return BuddyOptType_BUDDY_OPT_ADD
}

func (m *IMOptBuddyRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *IMOptBuddyRsp) GetOptRemark() string {
	if m != nil && m.OptRemark != nil {
		return *m.OptRemark
	}
	return ""
}

// 仅用于服务端
type IMOptBuddyResultRsp struct {
	UserId           *string       `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ResponseTime     *uint64       `protobuf:"varint,2,opt,name=response_time,json=responseTime" json:"response_time,omitempty"`
	OptType          *BuddyOptType `protobuf:"varint,3,opt,name=opt_type,json=optType,enum=youmai.BuddyOptType" json:"opt_type,omitempty"`
	Result           *int32        `protobuf:"varint,4,opt,name=result" json:"result,omitempty"`
	OptRemark        *string       `protobuf:"bytes,5,opt,name=opt_remark,json=optRemark" json:"opt_remark,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *IMOptBuddyResultRsp) Reset()                    { *m = IMOptBuddyResultRsp{} }
func (m *IMOptBuddyResultRsp) String() string            { return proto.CompactTextString(m) }
func (*IMOptBuddyResultRsp) ProtoMessage()               {}
func (*IMOptBuddyResultRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *IMOptBuddyResultRsp) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *IMOptBuddyResultRsp) GetResponseTime() uint64 {
	if m != nil && m.ResponseTime != nil {
		return *m.ResponseTime
	}
	return 0
}

func (m *IMOptBuddyResultRsp) GetOptType() BuddyOptType {
	if m != nil && m.OptType != nil {
		return *m.OptType
	}
	return BuddyOptType_BUDDY_OPT_ADD
}

func (m *IMOptBuddyResultRsp) GetResult() int32 {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return 0
}

func (m *IMOptBuddyResultRsp) GetOptRemark() string {
	if m != nil && m.OptRemark != nil {
		return *m.OptRemark
	}
	return ""
}

// 联系人昵称修改请求
type IMModiNickNameReq struct {
	// cmd id:		0x7218
	SrcUserId        *string `protobuf:"bytes,1,opt,name=src_user_id,json=srcUserId" json:"src_user_id,omitempty"`
	DestUserId       *string `protobuf:"bytes,3,opt,name=dest_user_id,json=destUserId" json:"dest_user_id,omitempty"`
	NickName         []byte  `protobuf:"bytes,20,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMModiNickNameReq) Reset()                    { *m = IMModiNickNameReq{} }
func (m *IMModiNickNameReq) String() string            { return proto.CompactTextString(m) }
func (*IMModiNickNameReq) ProtoMessage()               {}
func (*IMModiNickNameReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *IMModiNickNameReq) GetSrcUserId() string {
	if m != nil && m.SrcUserId != nil {
		return *m.SrcUserId
	}
	return ""
}

func (m *IMModiNickNameReq) GetDestUserId() string {
	if m != nil && m.DestUserId != nil {
		return *m.DestUserId
	}
	return ""
}

func (m *IMModiNickNameReq) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

// 联系人昵称修改返回
type IMModiNickNameRsp struct {
	// cmd id:		0x7219
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	NickName         []byte  `protobuf:"bytes,2,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	UpdateTime       *uint64 `protobuf:"varint,3,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMModiNickNameRsp) Reset()                    { *m = IMModiNickNameRsp{} }
func (m *IMModiNickNameRsp) String() string            { return proto.CompactTextString(m) }
func (*IMModiNickNameRsp) ProtoMessage()               {}
func (*IMModiNickNameRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *IMModiNickNameRsp) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *IMModiNickNameRsp) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *IMModiNickNameRsp) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

// 加好友申请信息
type IMBuddyReqInfo struct {
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	ReqStat          *uint32 `protobuf:"varint,2,opt,name=req_stat,json=reqStat" json:"req_stat,omitempty"`
	ReqTime          *uint64 `protobuf:"varint,3,opt,name=req_time,json=reqTime" json:"req_time,omitempty"`
	Remark           *string `protobuf:"bytes,4,opt,name=remark" json:"remark,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMBuddyReqInfo) Reset()                    { *m = IMBuddyReqInfo{} }
func (m *IMBuddyReqInfo) String() string            { return proto.CompactTextString(m) }
func (*IMBuddyReqInfo) ProtoMessage()               {}
func (*IMBuddyReqInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

func (m *IMBuddyReqInfo) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *IMBuddyReqInfo) GetReqStat() uint32 {
	if m != nil && m.ReqStat != nil {
		return *m.ReqStat
	}
	return 0
}

func (m *IMBuddyReqInfo) GetReqTime() uint64 {
	if m != nil && m.ReqTime != nil {
		return *m.ReqTime
	}
	return 0
}

func (m *IMBuddyReqInfo) GetRemark() string {
	if m != nil && m.Remark != nil {
		return *m.Remark
	}
	return ""
}

// /////////////////////////////////////////////////////
// 获取好友请求列表
type IMGetBuddyReqListReq struct {
	// cmd id:		0x721a
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UpdateTime       *uint64 `protobuf:"varint,2,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	PackIndex        *uint32 `protobuf:"varint,3,opt,name=pack_index,json=packIndex" json:"pack_index,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMGetBuddyReqListReq) Reset()                    { *m = IMGetBuddyReqListReq{} }
func (m *IMGetBuddyReqListReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetBuddyReqListReq) ProtoMessage()               {}
func (*IMGetBuddyReqListReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

func (m *IMGetBuddyReqListReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *IMGetBuddyReqListReq) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *IMGetBuddyReqListReq) GetPackIndex() uint32 {
	if m != nil && m.PackIndex != nil {
		return *m.PackIndex
	}
	return 0
}

type IMGetBuddyReqListRsp struct {
	// cmd id:		0x721b
	UpdateTime       *uint64           `protobuf:"varint,1,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	BuddysReqs       []*IMBuddyReqInfo `protobuf:"bytes,2,rep,name=BuddysReqs" json:"BuddysReqs,omitempty"`
	PackIndex        *uint32           `protobuf:"varint,3,opt,name=pack_index,json=packIndex" json:"pack_index,omitempty"`
	PackCount        *uint32           `protobuf:"varint,4,opt,name=pack_count,json=packCount" json:"pack_count,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *IMGetBuddyReqListRsp) Reset()                    { *m = IMGetBuddyReqListRsp{} }
func (m *IMGetBuddyReqListRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetBuddyReqListRsp) ProtoMessage()               {}
func (*IMGetBuddyReqListRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func (m *IMGetBuddyReqListRsp) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *IMGetBuddyReqListRsp) GetBuddysReqs() []*IMBuddyReqInfo {
	if m != nil {
		return m.BuddysReqs
	}
	return nil
}

func (m *IMGetBuddyReqListRsp) GetPackIndex() uint32 {
	if m != nil && m.PackIndex != nil {
		return *m.PackIndex
	}
	return 0
}

func (m *IMGetBuddyReqListRsp) GetPackCount() uint32 {
	if m != nil && m.PackCount != nil {
		return *m.PackCount
	}
	return 0
}

// 组织架构拉取
type OrgInfo struct {
	OrgId            *string `protobuf:"bytes,1,opt,name=org_id,json=orgId" json:"org_id,omitempty"`
	Type             *int32  `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Name             *string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Username         *string `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	Avator           *string `protobuf:"bytes,5,opt,name=avator" json:"avator,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *OrgInfo) Reset()                    { *m = OrgInfo{} }
func (m *OrgInfo) String() string            { return proto.CompactTextString(m) }
func (*OrgInfo) ProtoMessage()               {}
func (*OrgInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{12} }

func (m *OrgInfo) GetOrgId() string {
	if m != nil && m.OrgId != nil {
		return *m.OrgId
	}
	return ""
}

func (m *OrgInfo) GetType() int32 {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return 0
}

func (m *OrgInfo) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *OrgInfo) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *OrgInfo) GetAvator() string {
	if m != nil && m.Avator != nil {
		return *m.Avator
	}
	return ""
}

type IMGetOrgReq struct {
	OrgId            *string `protobuf:"bytes,1,opt,name=org_id,json=orgId" json:"org_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMGetOrgReq) Reset()                    { *m = IMGetOrgReq{} }
func (m *IMGetOrgReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetOrgReq) ProtoMessage()               {}
func (*IMGetOrgReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{13} }

func (m *IMGetOrgReq) GetOrgId() string {
	if m != nil && m.OrgId != nil {
		return *m.OrgId
	}
	return ""
}

type IMGetOrgRsp struct {
	OrgId            *string    `protobuf:"bytes,1,opt,name=org_id,json=orgId" json:"org_id,omitempty"`
	OrgList          []*OrgInfo `protobuf:"bytes,2,rep,name=org_list,json=orgList" json:"org_list,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *IMGetOrgRsp) Reset()                    { *m = IMGetOrgRsp{} }
func (m *IMGetOrgRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetOrgRsp) ProtoMessage()               {}
func (*IMGetOrgRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{14} }

func (m *IMGetOrgRsp) GetOrgId() string {
	if m != nil && m.OrgId != nil {
		return *m.OrgId
	}
	return ""
}

func (m *IMGetOrgRsp) GetOrgList() []*OrgInfo {
	if m != nil {
		return m.OrgList
	}
	return nil
}

// 用户资料拉取
type UserInfo struct {
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Phone            *string `protobuf:"bytes,2,opt,name=phone" json:"phone,omitempty"`
	NickName         *string `protobuf:"bytes,3,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	Avator           *string `protobuf:"bytes,4,opt,name=avator" json:"avator,omitempty"`
	Sex              *int32  `protobuf:"varint,5,opt,name=sex" json:"sex,omitempty"`
	Sign             *string `protobuf:"bytes,6,opt,name=sign" json:"sign,omitempty"`
	IsHx             *bool   `protobuf:"varint,20,opt,name=is_hx,json=isHx" json:"is_hx,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{15} }

func (m *UserInfo) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *UserInfo) GetPhone() string {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return ""
}

func (m *UserInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *UserInfo) GetAvator() string {
	if m != nil && m.Avator != nil {
		return *m.Avator
	}
	return ""
}

func (m *UserInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *UserInfo) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

func (m *UserInfo) GetIsHx() bool {
	if m != nil && m.IsHx != nil {
		return *m.IsHx
	}
	return false
}

type IMGetUserInfoReq struct {
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *IMGetUserInfoReq) Reset()                    { *m = IMGetUserInfoReq{} }
func (m *IMGetUserInfoReq) String() string            { return proto.CompactTextString(m) }
func (*IMGetUserInfoReq) ProtoMessage()               {}
func (*IMGetUserInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{16} }

func (m *IMGetUserInfoReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

type IMGetUserInfoRsp struct {
	UserInfo         *UserInfo   `protobuf:"bytes,1,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
	Result           *ResultCode `protobuf:"varint,2,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *IMGetUserInfoRsp) Reset()                    { *m = IMGetUserInfoRsp{} }
func (m *IMGetUserInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*IMGetUserInfoRsp) ProtoMessage()               {}
func (*IMGetUserInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{17} }

func (m *IMGetUserInfoRsp) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func (m *IMGetUserInfoRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

func init() {
	proto.RegisterType((*IMChangeAvatarReq)(nil), "youmai.IMChangeAvatarReq")
	proto.RegisterType((*IMChangeAvatarRsp)(nil), "youmai.IMChangeAvatarRsp")
	proto.RegisterType((*IMChangeSignInfoReq)(nil), "youmai.IMChangeSignInfoReq")
	proto.RegisterType((*IMChangeSignInfoRsp)(nil), "youmai.IMChangeSignInfoRsp")
	proto.RegisterType((*IMOptBuddyReq)(nil), "youmai.IMOptBuddyReq")
	proto.RegisterType((*IMOptBuddyRsp)(nil), "youmai.IMOptBuddyRsp")
	proto.RegisterType((*IMOptBuddyResultRsp)(nil), "youmai.IMOptBuddyResultRsp")
	proto.RegisterType((*IMModiNickNameReq)(nil), "youmai.IMModiNickNameReq")
	proto.RegisterType((*IMModiNickNameRsp)(nil), "youmai.IMModiNickNameRsp")
	proto.RegisterType((*IMBuddyReqInfo)(nil), "youmai.IMBuddyReqInfo")
	proto.RegisterType((*IMGetBuddyReqListReq)(nil), "youmai.IMGetBuddyReqListReq")
	proto.RegisterType((*IMGetBuddyReqListRsp)(nil), "youmai.IMGetBuddyReqListRsp")
	proto.RegisterType((*OrgInfo)(nil), "youmai.OrgInfo")
	proto.RegisterType((*IMGetOrgReq)(nil), "youmai.IMGetOrgReq")
	proto.RegisterType((*IMGetOrgRsp)(nil), "youmai.IMGetOrgRsp")
	proto.RegisterType((*UserInfo)(nil), "youmai.UserInfo")
	proto.RegisterType((*IMGetUserInfoReq)(nil), "youmai.IMGetUserInfoReq")
	proto.RegisterType((*IMGetUserInfoRsp)(nil), "youmai.IMGetUserInfoRsp")
	proto.RegisterEnum("youmai.BuddyOptType", BuddyOptType_name, BuddyOptType_value)
}

func init() { proto.RegisterFile("IM.Buddy.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 827 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x55, 0x4d, 0x8f, 0xdb, 0x36,
	0x10, 0x85, 0xfc, 0x29, 0x8f, 0xd7, 0x5b, 0x47, 0xd9, 0xa4, 0x6e, 0x82, 0xb4, 0x0b, 0xb5, 0x87,
	0xc5, 0x16, 0xdd, 0x02, 0x46, 0xd1, 0x7b, 0xb2, 0x2e, 0x5a, 0x01, 0x71, 0x1c, 0x28, 0xbb, 0x87,
	0x9c, 0x04, 0x42, 0x62, 0x64, 0xd6, 0xb6, 0x48, 0x93, 0x54, 0x6b, 0x03, 0xbd, 0x14, 0xf9, 0x25,
	0x3d, 0xf6, 0xd0, 0x63, 0x4f, 0xfd, 0x73, 0x05, 0x47, 0x1f, 0xb6, 0xec, 0xac, 0x8d, 0xee, 0xa1,
	0x40, 0x6e, 0xe4, 0xe3, 0x88, 0xf3, 0xf8, 0xe6, 0x8d, 0x06, 0x9c, 0xb7, 0x3c, 0x1d, 0x13, 0x76,
	0xf5, 0x22, 0x8d, 0xa2, 0xf5, 0x95, 0x90, 0x5c, 0x73, 0xa7, 0xb5, 0xe6, 0xe9, 0x82, 0xb0, 0x27,
	0xe5, 0x19, 0x51, 0x2c, 0xcc, 0xce, 0xdc, 0xf7, 0x16, 0x3c, 0xf0, 0xc6, 0xd7, 0x53, 0x92, 0xc4,
	0xf4, 0xf9, 0x2f, 0x44, 0x13, 0xe9, 0xd3, 0xa5, 0xf3, 0x29, 0xb4, 0x53, 0x45, 0x65, 0xc0, 0xa2,
	0x81, 0x75, 0x6e, 0x5d, 0x74, 0xfc, 0x96, 0xd9, 0x7a, 0x91, 0xf3, 0x08, 0x5a, 0x44, 0x08, 0x83,
	0xd7, 0x10, 0x6f, 0x12, 0x21, 0xbc, 0xc8, 0x79, 0x06, 0x40, 0xf0, 0xe3, 0x20, 0x95, 0xf3, 0x41,
	0x1d, 0x8f, 0x3a, 0x19, 0x72, 0x2b, 0xe7, 0xce, 0x17, 0xd0, 0x25, 0x5a, 0x93, 0x70, 0x1a, 0x44,
	0x44, 0x93, 0xc1, 0xd9, 0xb9, 0x75, 0x71, 0xe2, 0x43, 0x06, 0x8d, 0x88, 0x26, 0xee, 0xef, 0xfb,
	0x2c, 0x94, 0x70, 0x2e, 0xa1, 0x25, 0xa9, 0x4a, 0xe7, 0x1a, 0x49, 0x9c, 0x0e, 0x9d, 0xab, 0xec,
	0x21, 0x57, 0x3e, 0xa2, 0xd7, 0x3c, 0xa2, 0x7e, 0x1e, 0x61, 0x52, 0xa4, 0x22, 0x22, 0x9a, 0x06,
	0x9a, 0x2d, 0x28, 0xb2, 0x6b, 0xf8, 0x90, 0x41, 0x37, 0x6c, 0x41, 0x8f, 0x73, 0x78, 0x6f, 0xc1,
	0xc3, 0x82, 0xc3, 0x1b, 0x16, 0x27, 0x5e, 0xf2, 0x8e, 0xdf, 0x47, 0x8b, 0xa7, 0xd0, 0x51, 0x2c,
	0x4e, 0x02, 0x96, 0xbc, 0xe3, 0xb9, 0x14, 0xb6, 0xca, 0xef, 0xbb, 0x27, 0x8b, 0xff, 0x5d, 0x8b,
	0x3f, 0x2c, 0xe8, 0x79, 0xe3, 0x89, 0xd0, 0x68, 0x23, 0xa3, 0xc2, 0xe7, 0xd0, 0x55, 0x32, 0x0c,
	0xaa, 0x4a, 0x74, 0x94, 0x0c, 0x6f, 0x33, 0x31, 0xce, 0xe1, 0x24, 0xa2, 0x4a, 0x97, 0x01, 0x99,
	0x24, 0x60, 0xb0, 0x3c, 0xe2, 0x5b, 0xb0, 0xb9, 0xd0, 0x81, 0x5e, 0x0b, 0x8a, 0xb2, 0x9c, 0x0e,
	0xcf, 0x8a, 0x37, 0x60, 0x96, 0x89, 0xd0, 0x37, 0x6b, 0x41, 0xfd, 0x36, 0xcf, 0x16, 0xc6, 0x54,
	0xe6, 0x03, 0x49, 0x17, 0x44, 0xce, 0x06, 0x8d, 0x2c, 0x23, 0x17, 0xda, 0x47, 0xc0, 0xfd, 0xbb,
	0xca, 0x51, 0x89, 0xbb, 0x2b, 0xf5, 0x25, 0xf4, 0x24, 0x55, 0x82, 0x27, 0xaa, 0x22, 0xc9, 0x49,
	0x01, 0xa2, 0x28, 0xff, 0x99, 0xdf, 0xe3, 0xb2, 0x24, 0x86, 0x5b, 0xb3, 0x94, 0xbf, 0xca, 0xbb,
	0xb9, 0xcb, 0xfb, 0x1f, 0xac, 0xf0, 0x46, 0x5b, 0xf3, 0xcd, 0xc7, 0xc3, 0x5e, 0x9a, 0x46, 0x1d,
	0xf3, 0x88, 0xbd, 0x62, 0xe1, 0xec, 0x15, 0x59, 0xd0, 0xfb, 0x98, 0xa3, 0xbe, 0x67, 0x8e, 0xa7,
	0xd0, 0x49, 0x58, 0x38, 0x0b, 0x12, 0xb2, 0xa0, 0xb9, 0x1f, 0xed, 0x24, 0xcf, 0xe0, 0xfe, 0xbc,
	0x97, 0xf3, 0x90, 0x5c, 0x95, 0xab, 0x6a, 0xd5, 0xab, 0x76, 0x5b, 0xa3, 0xbe, 0xdb, 0x1a, 0xee,
	0xaf, 0x70, 0xea, 0x8d, 0x0b, 0xd7, 0x63, 0xcb, 0xde, 0x99, 0xe8, 0x33, 0xb0, 0x25, 0x5d, 0x06,
	0x4a, 0x13, 0x8d, 0x79, 0x7a, 0x7e, 0x5b, 0xd2, 0xe5, 0x1b, 0x4d, 0x74, 0x71, 0xb4, 0x95, 0xc3,
	0x1c, 0x61, 0xa1, 0x50, 0xf7, 0x2d, 0x47, 0xe7, 0x3b, 0x97, 0xc3, 0x99, 0x37, 0xfe, 0x91, 0x96,
	0x1d, 0xf7, 0x92, 0x29, 0x7d, 0xf0, 0xf7, 0x73, 0xb4, 0xcb, 0x9f, 0x01, 0x08, 0x12, 0xce, 0x02,
	0x96, 0x44, 0x74, 0x85, 0x34, 0x7a, 0x7e, 0xc7, 0x20, 0x9e, 0x01, 0xdc, 0xbf, 0xac, 0x0f, 0x65,
	0x54, 0x62, 0xf7, 0x62, 0x6b, 0xef, 0xe2, 0xef, 0x01, 0xf0, 0x1b, 0xe5, 0xd3, 0xa5, 0x1a, 0xd4,
	0xce, 0xeb, 0x17, 0xdd, 0xe1, 0xe3, 0xc2, 0x6d, 0x55, 0xf5, 0xfc, 0xad, 0xc8, 0x23, 0x84, 0xca,
	0xe3, 0x90, 0xa7, 0x49, 0xe6, 0xca, 0xfc, 0xf8, 0xda, 0x00, 0xee, 0x6f, 0xd0, 0x9e, 0xc8, 0x18,
	0x4b, 0xf2, 0x08, 0x5a, 0x5c, 0xc6, 0x1b, 0x49, 0x9a, 0x5c, 0xc6, 0x5e, 0xe4, 0x38, 0xd0, 0x40,
	0xff, 0xd7, 0xd0, 0xd0, 0xb8, 0x36, 0x18, 0x1a, 0x21, 0xb3, 0x1c, 0xae, 0x9d, 0x27, 0x60, 0x1b,
	0x0d, 0x11, 0xcf, 0x8a, 0x50, 0xee, 0x4d, 0x79, 0xcc, 0xdc, 0xe2, 0x32, 0xb7, 0x7e, 0xbe, 0x73,
	0xbf, 0x82, 0x2e, 0x8a, 0x35, 0x91, 0xb1, 0xa9, 0xca, 0x87, 0x19, 0xb8, 0xaf, 0xb7, 0xa2, 0x94,
	0xb8, 0x8b, 0xe7, 0x25, 0xd8, 0x06, 0x9e, 0x33, 0xa5, 0x73, 0xf5, 0x3e, 0x29, 0xd4, 0xcb, 0x5f,
	0xe8, 0xb7, 0xb9, 0x8c, 0x4d, 0x3d, 0xdc, 0x3f, 0x2d, 0xb0, 0xb1, 0x47, 0x0e, 0x5a, 0xf1, 0x0c,
	0x9a, 0x62, 0xca, 0x13, 0x5a, 0x4c, 0x22, 0xdc, 0x54, 0x3b, 0x21, 0x9f, 0x44, 0x65, 0x27, 0x6c,
	0x1e, 0xda, 0xd8, 0x7e, 0xa8, 0xd3, 0x87, 0xba, 0xa2, 0x2b, 0x7c, 0x7d, 0xd3, 0x37, 0x4b, 0x23,
	0xa1, 0x99, 0x5f, 0x83, 0x56, 0x26, 0xa1, 0x59, 0x3b, 0x0f, 0xa1, 0xc9, 0x54, 0x30, 0x5d, 0x61,
	0xaf, 0xda, 0x7e, 0x83, 0xa9, 0x9f, 0x56, 0xee, 0xd7, 0xd0, 0xc7, 0xd7, 0x17, 0x7c, 0x0f, 0xd9,
	0xd7, 0x5d, 0xec, 0x06, 0x2b, 0xe1, 0x7c, 0x03, 0x9d, 0x2c, 0xd8, 0x8c, 0x4e, 0x13, 0xde, 0x1d,
	0xf6, 0x0b, 0x65, 0xca, 0x38, 0xac, 0x15, 0xca, 0xb1, 0x99, 0x89, 0xb5, 0x63, 0x33, 0xf1, 0xf2,
	0x3b, 0x38, 0xd9, 0xfe, 0x0f, 0x3a, 0x0f, 0xa0, 0xf7, 0xe2, 0x76, 0x34, 0x7a, 0x1b, 0x4c, 0x5e,
	0xdf, 0x04, 0xcf, 0x47, 0xa3, 0xbe, 0x55, 0x85, 0x46, 0x3f, 0xbc, 0xec, 0xd7, 0xfe, 0x0d, 0x00,
	0x00, 0xff, 0xff, 0x96, 0x69, 0x21, 0x30, 0x4e, 0x09, 0x00, 0x00,
}
