// Code generated by protoc-gen-go.
// source: IM.Group.proto
// DO NOT EDIT!

package youmai

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GroupMemberOptType int32

const (
	GroupMemberOptType_GROUP_MEMBER_OPT_ADD GroupMemberOptType = 1
	GroupMemberOptType_GROUP_MEMBER_OPT_DEL GroupMemberOptType = 2
)

var GroupMemberOptType_name = map[int32]string{
	1: "GROUP_MEMBER_OPT_ADD",
	2: "GROUP_MEMBER_OPT_DEL",
}
var GroupMemberOptType_value = map[string]int32{
	"GROUP_MEMBER_OPT_ADD": 1,
	"GROUP_MEMBER_OPT_DEL": 2,
}

func (x GroupMemberOptType) Enum() *GroupMemberOptType {
	p := new(GroupMemberOptType)
	*p = x
	return p
}
func (x GroupMemberOptType) String() string {
	return proto.EnumName(GroupMemberOptType_name, int32(x))
}
func (x *GroupMemberOptType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GroupMemberOptType_value, data, "GroupMemberOptType")
	if err != nil {
		return err
	}
	*x = GroupMemberOptType(value)
	return nil
}
func (GroupMemberOptType) EnumDescriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

type GroupItem struct {
	GroupId          *uint32 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	InfoUpdateTime   *uint64 `protobuf:"varint,2,opt,name=info_update_time,json=infoUpdateTime" json:"info_update_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupItem) Reset()                    { *m = GroupItem{} }
func (m *GroupItem) String() string            { return proto.CompactTextString(m) }
func (*GroupItem) ProtoMessage()               {}
func (*GroupItem) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *GroupItem) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupItem) GetInfoUpdateTime() uint64 {
	if m != nil && m.InfoUpdateTime != nil {
		return *m.InfoUpdateTime
	}
	return 0
}

type GroupMemberItem struct {
	MemberId         *string `protobuf:"bytes,1,opt,name=member_id,json=memberId" json:"member_id,omitempty"`
	MemberName       *string `protobuf:"bytes,2,opt,name=member_name,json=memberName" json:"member_name,omitempty"`
	UserName         *string `protobuf:"bytes,3,opt,name=user_name,json=userName" json:"user_name,omitempty"`
	MemberRole       *uint32 `protobuf:"varint,4,opt,name=member_role,json=memberRole" json:"member_role,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupMemberItem) Reset()                    { *m = GroupMemberItem{} }
func (m *GroupMemberItem) String() string            { return proto.CompactTextString(m) }
func (*GroupMemberItem) ProtoMessage()               {}
func (*GroupMemberItem) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *GroupMemberItem) GetMemberId() string {
	if m != nil && m.MemberId != nil {
		return *m.MemberId
	}
	return ""
}

func (m *GroupMemberItem) GetMemberName() string {
	if m != nil && m.MemberName != nil {
		return *m.MemberName
	}
	return ""
}

func (m *GroupMemberItem) GetUserName() string {
	if m != nil && m.UserName != nil {
		return *m.UserName
	}
	return ""
}

func (m *GroupMemberItem) GetMemberRole() uint32 {
	if m != nil && m.MemberRole != nil {
		return *m.MemberRole
	}
	return 0
}

type GroupInfo struct {
	GroupId          *uint32 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	GroupName        *string `protobuf:"bytes,2,opt,name=group_name,json=groupName" json:"group_name,omitempty"`
	OwnerId          *string `protobuf:"bytes,3,opt,name=owner_id,json=ownerId" json:"owner_id,omitempty"`
	GroupAvatar      *string `protobuf:"bytes,4,opt,name=group_avatar,json=groupAvatar" json:"group_avatar,omitempty"`
	Topic            *string `protobuf:"bytes,5,opt,name=topic" json:"topic,omitempty"`
	InfoUpdateTime   *uint64 `protobuf:"varint,6,opt,name=info_update_time,json=infoUpdateTime" json:"info_update_time,omitempty"`
	GroupMemberCount *uint32 `protobuf:"varint,7,opt,name=group_member_count,json=groupMemberCount" json:"group_member_count,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupInfo) Reset()                    { *m = GroupInfo{} }
func (m *GroupInfo) String() string            { return proto.CompactTextString(m) }
func (*GroupInfo) ProtoMessage()               {}
func (*GroupInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *GroupInfo) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupInfo) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *GroupInfo) GetOwnerId() string {
	if m != nil && m.OwnerId != nil {
		return *m.OwnerId
	}
	return ""
}

func (m *GroupInfo) GetGroupAvatar() string {
	if m != nil && m.GroupAvatar != nil {
		return *m.GroupAvatar
	}
	return ""
}

func (m *GroupInfo) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *GroupInfo) GetInfoUpdateTime() uint64 {
	if m != nil && m.InfoUpdateTime != nil {
		return *m.InfoUpdateTime
	}
	return 0
}

func (m *GroupInfo) GetGroupMemberCount() uint32 {
	if m != nil && m.GroupMemberCount != nil {
		return *m.GroupMemberCount
	}
	return 0
}

type GroupCreateReq struct {
	// cmd id:	 CID_GROUP_CREATE_REQ
	UserId           *string            `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	MemberList       []*GroupMemberItem `protobuf:"bytes,2,rep,name=member_list,json=memberList" json:"member_list,omitempty"`
	GroupName        *string            `protobuf:"bytes,3,opt,name=group_name,json=groupName" json:"group_name,omitempty"`
	GroupAvatar      *string            `protobuf:"bytes,4,opt,name=group_avatar,json=groupAvatar" json:"group_avatar,omitempty"`
	Topic            *string            `protobuf:"bytes,5,opt,name=topic" json:"topic,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GroupCreateReq) Reset()                    { *m = GroupCreateReq{} }
func (m *GroupCreateReq) String() string            { return proto.CompactTextString(m) }
func (*GroupCreateReq) ProtoMessage()               {}
func (*GroupCreateReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *GroupCreateReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *GroupCreateReq) GetMemberList() []*GroupMemberItem {
	if m != nil {
		return m.MemberList
	}
	return nil
}

func (m *GroupCreateReq) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *GroupCreateReq) GetGroupAvatar() string {
	if m != nil && m.GroupAvatar != nil {
		return *m.GroupAvatar
	}
	return ""
}

func (m *GroupCreateReq) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

type GroupCreateRsp struct {
	// cmd id:	 CID_GROUP_CREATE_RSP
	GroupId          *uint32            `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	UserId           *string            `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	MemberList       []*GroupMemberItem `protobuf:"bytes,3,rep,name=member_list,json=memberList" json:"member_list,omitempty"`
	UpdateTime       *uint64            `protobuf:"varint,4,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	Result           *ResultCode        `protobuf:"varint,10,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GroupCreateRsp) Reset()                    { *m = GroupCreateRsp{} }
func (m *GroupCreateRsp) String() string            { return proto.CompactTextString(m) }
func (*GroupCreateRsp) ProtoMessage()               {}
func (*GroupCreateRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *GroupCreateRsp) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupCreateRsp) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *GroupCreateRsp) GetMemberList() []*GroupMemberItem {
	if m != nil {
		return m.MemberList
	}
	return nil
}

func (m *GroupCreateRsp) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *GroupCreateRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

type GroupDissolveReq struct {
	// cmd id:	 CID_GROUP_DISSOLVE_REQ
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupId          *uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupDissolveReq) Reset()                    { *m = GroupDissolveReq{} }
func (m *GroupDissolveReq) String() string            { return proto.CompactTextString(m) }
func (*GroupDissolveReq) ProtoMessage()               {}
func (*GroupDissolveReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *GroupDissolveReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *GroupDissolveReq) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

type GroupDissolveRsp struct {
	// cmd id:	 CID_GROUP_DISSOLVE_RSP
	GroupId          *uint32     `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Result           *ResultCode `protobuf:"varint,10,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GroupDissolveRsp) Reset()                    { *m = GroupDissolveRsp{} }
func (m *GroupDissolveRsp) String() string            { return proto.CompactTextString(m) }
func (*GroupDissolveRsp) ProtoMessage()               {}
func (*GroupDissolveRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *GroupDissolveRsp) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupDissolveRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

// 群操作通知
type GroupOptNotify struct {
	// cmd id:			CID_GROUP_OPT_NOTIFY
	OptType          *uint32 `protobuf:"varint,1,opt,name=opt_type,json=optType" json:"opt_type,omitempty"`
	GroupId          *uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupOptNotify) Reset()                    { *m = GroupOptNotify{} }
func (m *GroupOptNotify) String() string            { return proto.CompactTextString(m) }
func (*GroupOptNotify) ProtoMessage()               {}
func (*GroupOptNotify) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

func (m *GroupOptNotify) GetOptType() uint32 {
	if m != nil && m.OptType != nil {
		return *m.OptType
	}
	return 0
}

func (m *GroupOptNotify) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

// 添加/删除群成员
type GroupMemberChangeReq struct {
	// cmd id:	 CID_GROUP_CHANGE_MEMBER_REQ
	UserId           *string             `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupId          *uint32             `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	MemberList       []*GroupMemberItem  `protobuf:"bytes,3,rep,name=member_list,json=memberList" json:"member_list,omitempty"`
	Type             *GroupMemberOptType `protobuf:"varint,4,opt,name=type,enum=youmai.GroupMemberOptType" json:"type,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GroupMemberChangeReq) Reset()                    { *m = GroupMemberChangeReq{} }
func (m *GroupMemberChangeReq) String() string            { return proto.CompactTextString(m) }
func (*GroupMemberChangeReq) ProtoMessage()               {}
func (*GroupMemberChangeReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *GroupMemberChangeReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *GroupMemberChangeReq) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupMemberChangeReq) GetMemberList() []*GroupMemberItem {
	if m != nil {
		return m.MemberList
	}
	return nil
}

func (m *GroupMemberChangeReq) GetType() GroupMemberOptType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return GroupMemberOptType_GROUP_MEMBER_OPT_ADD
}

type GroupMemberChangeRsp struct {
	GroupId          *uint32             `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	MemberList       []*GroupMemberItem  `protobuf:"bytes,2,rep,name=member_list,json=memberList" json:"member_list,omitempty"`
	Type             *GroupMemberOptType `protobuf:"varint,3,opt,name=type,enum=youmai.GroupMemberOptType" json:"type,omitempty"`
	UpdateTime       *uint64             `protobuf:"varint,4,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	Result           *ResultCode         `protobuf:"varint,10,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GroupMemberChangeRsp) Reset()                    { *m = GroupMemberChangeRsp{} }
func (m *GroupMemberChangeRsp) String() string            { return proto.CompactTextString(m) }
func (*GroupMemberChangeRsp) ProtoMessage()               {}
func (*GroupMemberChangeRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

func (m *GroupMemberChangeRsp) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupMemberChangeRsp) GetMemberList() []*GroupMemberItem {
	if m != nil {
		return m.MemberList
	}
	return nil
}

func (m *GroupMemberChangeRsp) GetType() GroupMemberOptType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return GroupMemberOptType_GROUP_MEMBER_OPT_ADD
}

func (m *GroupMemberChangeRsp) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *GroupMemberChangeRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

type GroupMemberChangeNotify struct {
	// cmd id:	 CID_GROUP_CHANGE_MEMBER_NOTIFY
	GroupId          *uint32             `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	MemberList       []*GroupMemberItem  `protobuf:"bytes,2,rep,name=member_list,json=memberList" json:"member_list,omitempty"`
	Type             *GroupMemberOptType `protobuf:"varint,3,opt,name=type,enum=youmai.GroupMemberOptType" json:"type,omitempty"`
	UpdateTime       *uint64             `protobuf:"varint,4,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *GroupMemberChangeNotify) Reset()                    { *m = GroupMemberChangeNotify{} }
func (m *GroupMemberChangeNotify) String() string            { return proto.CompactTextString(m) }
func (*GroupMemberChangeNotify) ProtoMessage()               {}
func (*GroupMemberChangeNotify) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *GroupMemberChangeNotify) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupMemberChangeNotify) GetMemberList() []*GroupMemberItem {
	if m != nil {
		return m.MemberList
	}
	return nil
}

func (m *GroupMemberChangeNotify) GetType() GroupMemberOptType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return GroupMemberOptType_GROUP_MEMBER_OPT_ADD
}

func (m *GroupMemberChangeNotify) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

// 获取群列表  拉取条件：点击群组图标拉取 （先用本地数据展示，再后台更新）
type GroupListReq struct {
	// cmd id:	 CID_GROUP_LIST_REQ
	UserId           *string      `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupItemList    []*GroupItem `protobuf:"bytes,2,rep,name=group_item_list,json=groupItemList" json:"group_item_list,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *GroupListReq) Reset()                    { *m = GroupListReq{} }
func (m *GroupListReq) String() string            { return proto.CompactTextString(m) }
func (*GroupListReq) ProtoMessage()               {}
func (*GroupListReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

func (m *GroupListReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *GroupListReq) GetGroupItemList() []*GroupItem {
	if m != nil {
		return m.GroupItemList
	}
	return nil
}

type GroupListRsp struct {
	// cmd id:	 CID_GROUP_LIST_RSP
	GroupInfoList     []*GroupInfo `protobuf:"bytes,1,rep,name=group_info_list,json=groupInfoList" json:"group_info_list,omitempty"`
	LatestGroupIdList []uint32     `protobuf:"varint,2,rep,name=latest_group_id_list,json=latestGroupIdList" json:"latest_group_id_list,omitempty"`
	Result            *ResultCode  `protobuf:"varint,10,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	XXX_unrecognized  []byte       `json:"-"`
}

func (m *GroupListRsp) Reset()                    { *m = GroupListRsp{} }
func (m *GroupListRsp) String() string            { return proto.CompactTextString(m) }
func (*GroupListRsp) ProtoMessage()               {}
func (*GroupListRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *GroupListRsp) GetGroupInfoList() []*GroupInfo {
	if m != nil {
		return m.GroupInfoList
	}
	return nil
}

func (m *GroupListRsp) GetLatestGroupIdList() []uint32 {
	if m != nil {
		return m.LatestGroupIdList
	}
	return nil
}

func (m *GroupListRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

// 获取群成员  拉取条件：点击成员列表图标拉取
type GroupMemberReq struct {
	// cmd id:			CID_GROUP_MEMBER_REQ
	GroupId          *uint32 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	UserId           *string `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	UpdateTime       *uint64 `protobuf:"varint,3,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupMemberReq) Reset()                    { *m = GroupMemberReq{} }
func (m *GroupMemberReq) String() string            { return proto.CompactTextString(m) }
func (*GroupMemberReq) ProtoMessage()               {}
func (*GroupMemberReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

func (m *GroupMemberReq) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupMemberReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *GroupMemberReq) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

type GroupMemberRsp struct {
	// cmd id:			CID_GROUP_MEMBER_RSP
	GroupId          *uint32            `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	MemberList       []*GroupMemberItem `protobuf:"bytes,2,rep,name=member_list,json=memberList" json:"member_list,omitempty"`
	UpdateTime       *uint64            `protobuf:"varint,3,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	Result           *ResultCode        `protobuf:"varint,10,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *GroupMemberRsp) Reset()                    { *m = GroupMemberRsp{} }
func (m *GroupMemberRsp) String() string            { return proto.CompactTextString(m) }
func (*GroupMemberRsp) ProtoMessage()               {}
func (*GroupMemberRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *GroupMemberRsp) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupMemberRsp) GetMemberList() []*GroupMemberItem {
	if m != nil {
		return m.MemberList
	}
	return nil
}

func (m *GroupMemberRsp) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

func (m *GroupMemberRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

// 获取群详细信息
type GroupInfoReq struct {
	// cmd id:			CID_GROUP_INFO_REQ
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupId          *uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	UpdateTime       *uint64 `protobuf:"varint,3,opt,name=update_time,json=updateTime" json:"update_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupInfoReq) Reset()                    { *m = GroupInfoReq{} }
func (m *GroupInfoReq) String() string            { return proto.CompactTextString(m) }
func (*GroupInfoReq) ProtoMessage()               {}
func (*GroupInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func (m *GroupInfoReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *GroupInfoReq) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupInfoReq) GetUpdateTime() uint64 {
	if m != nil && m.UpdateTime != nil {
		return *m.UpdateTime
	}
	return 0
}

type GroupInfoRsp struct {
	// cmd id:			CID_GROUP_INFO_REQ
	GroupInfo        *GroupInfo  `protobuf:"bytes,1,opt,name=group_info,json=groupInfo" json:"group_info,omitempty"`
	Update           *bool       `protobuf:"varint,2,opt,name=update" json:"update,omitempty"`
	Result           *ResultCode `protobuf:"varint,10,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GroupInfoRsp) Reset()                    { *m = GroupInfoRsp{} }
func (m *GroupInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*GroupInfoRsp) ProtoMessage()               {}
func (*GroupInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{16} }

func (m *GroupInfoRsp) GetGroupInfo() *GroupInfo {
	if m != nil {
		return m.GroupInfo
	}
	return nil
}

func (m *GroupInfoRsp) GetUpdate() bool {
	if m != nil && m.Update != nil {
		return *m.Update
	}
	return false
}

func (m *GroupInfoRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

// 群资料修改
type GroupInfoModifyReq struct {
	// cmd id:			CID_GROUP_INFO_MODIFY_REQ
	UserId           *string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	GroupId          *uint32 `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	GroupName        *string `protobuf:"bytes,3,opt,name=group_name,json=groupName" json:"group_name,omitempty"`
	GroupAvatar      *string `protobuf:"bytes,4,opt,name=group_avatar,json=groupAvatar" json:"group_avatar,omitempty"`
	Topic            *string `protobuf:"bytes,5,opt,name=topic" json:"topic,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GroupInfoModifyReq) Reset()                    { *m = GroupInfoModifyReq{} }
func (m *GroupInfoModifyReq) String() string            { return proto.CompactTextString(m) }
func (*GroupInfoModifyReq) ProtoMessage()               {}
func (*GroupInfoModifyReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{17} }

func (m *GroupInfoModifyReq) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *GroupInfoModifyReq) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupInfoModifyReq) GetGroupName() string {
	if m != nil && m.GroupName != nil {
		return *m.GroupName
	}
	return ""
}

func (m *GroupInfoModifyReq) GetGroupAvatar() string {
	if m != nil && m.GroupAvatar != nil {
		return *m.GroupAvatar
	}
	return ""
}

func (m *GroupInfoModifyReq) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

// 群资料修改返回
// + 增加返回群组ID bob 2016.08.22
type GroupInfoModifyRsp struct {
	// cmd id:			CID_GROUP_INFO_MODIFY_RSP
	Result           *ResultCode `protobuf:"varint,1,opt,name=result,enum=youmai.ResultCode" json:"result,omitempty"`
	GroupId          *uint32     `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	GroupInfo        *GroupInfo  `protobuf:"bytes,3,opt,name=group_info,json=groupInfo" json:"group_info,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *GroupInfoModifyRsp) Reset()                    { *m = GroupInfoModifyRsp{} }
func (m *GroupInfoModifyRsp) String() string            { return proto.CompactTextString(m) }
func (*GroupInfoModifyRsp) ProtoMessage()               {}
func (*GroupInfoModifyRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{18} }

func (m *GroupInfoModifyRsp) GetResult() ResultCode {
	if m != nil && m.Result != nil {
		return *m.Result
	}
	return ResultCode_RESULT_CODE_SUCCESS
}

func (m *GroupInfoModifyRsp) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *GroupInfoModifyRsp) GetGroupInfo() *GroupInfo {
	if m != nil {
		return m.GroupInfo
	}
	return nil
}

// 群资料修改通知
type IMGroupInfoModifyNotify struct {
	GroupId          *uint32    `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	GroupInfo        *GroupInfo `protobuf:"bytes,2,opt,name=group_info,json=groupInfo" json:"group_info,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *IMGroupInfoModifyNotify) Reset()                    { *m = IMGroupInfoModifyNotify{} }
func (m *IMGroupInfoModifyNotify) String() string            { return proto.CompactTextString(m) }
func (*IMGroupInfoModifyNotify) ProtoMessage()               {}
func (*IMGroupInfoModifyNotify) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{19} }

func (m *IMGroupInfoModifyNotify) GetGroupId() uint32 {
	if m != nil && m.GroupId != nil {
		return *m.GroupId
	}
	return 0
}

func (m *IMGroupInfoModifyNotify) GetGroupInfo() *GroupInfo {
	if m != nil {
		return m.GroupInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*GroupItem)(nil), "youmai.GroupItem")
	proto.RegisterType((*GroupMemberItem)(nil), "youmai.GroupMemberItem")
	proto.RegisterType((*GroupInfo)(nil), "youmai.GroupInfo")
	proto.RegisterType((*GroupCreateReq)(nil), "youmai.GroupCreateReq")
	proto.RegisterType((*GroupCreateRsp)(nil), "youmai.GroupCreateRsp")
	proto.RegisterType((*GroupDissolveReq)(nil), "youmai.GroupDissolveReq")
	proto.RegisterType((*GroupDissolveRsp)(nil), "youmai.GroupDissolveRsp")
	proto.RegisterType((*GroupOptNotify)(nil), "youmai.GroupOptNotify")
	proto.RegisterType((*GroupMemberChangeReq)(nil), "youmai.GroupMemberChangeReq")
	proto.RegisterType((*GroupMemberChangeRsp)(nil), "youmai.GroupMemberChangeRsp")
	proto.RegisterType((*GroupMemberChangeNotify)(nil), "youmai.GroupMemberChangeNotify")
	proto.RegisterType((*GroupListReq)(nil), "youmai.GroupListReq")
	proto.RegisterType((*GroupListRsp)(nil), "youmai.GroupListRsp")
	proto.RegisterType((*GroupMemberReq)(nil), "youmai.GroupMemberReq")
	proto.RegisterType((*GroupMemberRsp)(nil), "youmai.GroupMemberRsp")
	proto.RegisterType((*GroupInfoReq)(nil), "youmai.GroupInfoReq")
	proto.RegisterType((*GroupInfoRsp)(nil), "youmai.GroupInfoRsp")
	proto.RegisterType((*GroupInfoModifyReq)(nil), "youmai.GroupInfoModifyReq")
	proto.RegisterType((*GroupInfoModifyRsp)(nil), "youmai.GroupInfoModifyRsp")
	proto.RegisterType((*IMGroupInfoModifyNotify)(nil), "youmai.IMGroupInfoModifyNotify")
	proto.RegisterEnum("youmai.GroupMemberOptType", GroupMemberOptType_name, GroupMemberOptType_value)
}

func init() { proto.RegisterFile("IM.Group.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 775 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xda, 0x4a,
	0x14, 0xd6, 0x00, 0xe1, 0xe7, 0x90, 0x1f, 0x32, 0x42, 0x17, 0x27, 0x57, 0x57, 0xe1, 0x7a, 0x85,
	0xa2, 0x8a, 0x56, 0x59, 0xb5, 0xcb, 0x04, 0xd2, 0x14, 0x29, 0x84, 0xc8, 0x4a, 0x16, 0x59, 0x59,
	0x0e, 0x1e, 0xa8, 0x25, 0xec, 0x71, 0xf1, 0x38, 0x15, 0xfb, 0x6e, 0xf3, 0x0e, 0x5d, 0xf5, 0x01,
	0xaa, 0xee, 0xba, 0xe8, 0x03, 0xf4, 0x45, 0xba, 0xed, 0x1b, 0x54, 0x3e, 0x63, 0x83, 0x21, 0x96,
	0x09, 0xb4, 0x91, 0xba, 0x63, 0xce, 0xf1, 0xf9, 0xce, 0xf7, 0x7d, 0xe7, 0xcc, 0x00, 0xf4, 0x86,
	0xfb, 0x5d, 0xc3, 0x6a, 0x9e, 0x8d, 0xb9, 0xef, 0x36, 0xdd, 0x31, 0x17, 0x9c, 0xe6, 0x27, 0xdc,
	0xb7, 0x0d, 0x6b, 0x3f, 0xca, 0x9d, 0x18, 0x9e, 0xd5, 0x97, 0x39, 0xf5, 0x12, 0x4a, 0xf8, 0x69,
	0x47, 0x30, 0x9b, 0xee, 0x41, 0x71, 0x18, 0x1c, 0x74, 0xcb, 0x54, 0x48, 0x9d, 0x34, 0xb6, 0xb4,
	0x02, 0x9e, 0x3b, 0x26, 0x6d, 0x40, 0xc5, 0x72, 0x06, 0x5c, 0xf7, 0x5d, 0xd3, 0x10, 0x4c, 0x17,
	0x96, 0xcd, 0x94, 0x4c, 0x9d, 0x34, 0x72, 0xda, 0x76, 0x10, 0xbf, 0xc6, 0xf0, 0x95, 0x65, 0x33,
	0xf5, 0x9e, 0xc0, 0x0e, 0x42, 0x76, 0x99, 0x7d, 0xcb, 0xc6, 0x08, 0xfc, 0x2f, 0x94, 0x6c, 0x3c,
	0x45, 0xc8, 0x25, 0xad, 0x28, 0x03, 0x1d, 0x93, 0x1e, 0x40, 0x39, 0x4c, 0x3a, 0x46, 0x88, 0x5a,
	0xd2, 0x40, 0x86, 0x2e, 0x0c, 0x9b, 0x05, 0xd5, 0xbe, 0x17, 0xa5, 0xb3, 0xb2, 0x3a, 0x08, 0x60,
	0x72, 0x56, 0x3d, 0xe6, 0x23, 0xa6, 0xe4, 0x90, 0x76, 0x58, 0xad, 0xf1, 0x11, 0x53, 0x7f, 0x92,
	0x48, 0xa2, 0x33, 0xe0, 0x69, 0x12, 0xff, 0x03, 0x90, 0xa9, 0x18, 0x8d, 0x12, 0x46, 0xb0, 0xd1,
	0x1e, 0x14, 0xf9, 0x7b, 0x47, 0x4a, 0x90, 0x24, 0x0a, 0x78, 0xee, 0x98, 0xf4, 0x7f, 0xd8, 0x94,
	0x95, 0xc6, 0x9d, 0x21, 0x8c, 0x31, 0x92, 0x28, 0x69, 0x65, 0x8c, 0x1d, 0x63, 0x88, 0x56, 0x61,
	0x43, 0x70, 0xd7, 0xea, 0x2b, 0x1b, 0x98, 0x93, 0x87, 0x44, 0x57, 0xf3, 0x49, 0xae, 0xd2, 0x67,
	0x40, 0x65, 0x8b, 0x50, 0x6c, 0x9f, 0xfb, 0x8e, 0x50, 0x0a, 0xa8, 0xa0, 0x32, 0x9c, 0xd9, 0xdd,
	0x0a, 0xe2, 0xea, 0x57, 0x02, 0xdb, 0xa8, 0xb9, 0x35, 0x66, 0x86, 0x60, 0x1a, 0x7b, 0x47, 0x6b,
	0x50, 0x40, 0x13, 0xa7, 0x03, 0xc8, 0x07, 0xc7, 0x8e, 0x49, 0x5f, 0x4e, 0x0d, 0x1c, 0x59, 0x9e,
	0x50, 0x32, 0xf5, 0x6c, 0xa3, 0x7c, 0x54, 0x6b, 0xca, 0x9d, 0x69, 0x2e, 0x4c, 0x32, 0x72, 0xf6,
	0xdc, 0xf2, 0xc4, 0x82, 0x61, 0xd9, 0x45, 0xc3, 0xd6, 0x75, 0x45, 0xfd, 0xbe, 0xc0, 0xde, 0x73,
	0xd3, 0xc6, 0x16, 0x13, 0x96, 0x49, 0x13, 0x96, 0x7d, 0xbc, 0xb0, 0x03, 0x28, 0xc7, 0x27, 0x92,
	0xc3, 0x89, 0x80, 0x3f, 0x9b, 0xc6, 0x21, 0xe4, 0xc7, 0xcc, 0xf3, 0x47, 0x42, 0x81, 0x3a, 0x69,
	0x6c, 0x1f, 0xd1, 0x08, 0x55, 0xc3, 0x68, 0x8b, 0x9b, 0x4c, 0x0b, 0xbf, 0x50, 0x5f, 0x43, 0x05,
	0x7b, 0xb5, 0x2d, 0xcf, 0xe3, 0xa3, 0xbb, 0xf4, 0x61, 0xc4, 0x75, 0x66, 0xe6, 0x74, 0xaa, 0x37,
	0x8b, 0x38, 0xe9, 0xb6, 0xac, 0x46, 0x51, 0xfa, 0xdd, 0x73, 0xc5, 0x05, 0x17, 0xd6, 0x60, 0x82,
	0xcb, 0xee, 0x0a, 0x5d, 0x4c, 0x5c, 0x16, 0x01, 0x73, 0x57, 0x5c, 0x4d, 0x5c, 0x96, 0x46, 0xf1,
	0x0b, 0x81, 0x6a, 0xcc, 0xd7, 0xd6, 0x5b, 0xc3, 0x19, 0xae, 0xab, 0xf7, 0x37, 0xc6, 0xd7, 0x84,
	0x1c, 0x12, 0xcf, 0xa1, 0xf0, 0xfd, 0x84, 0x92, 0x9e, 0xd4, 0xa2, 0xe1, 0x77, 0xea, 0x8f, 0x44,
	0xda, 0xe9, 0xf6, 0xae, 0x7f, 0x6b, 0x22, 0x76, 0xd9, 0xc7, 0xb1, 0xfb, 0xb3, 0xcb, 0xf8, 0x8d,
	0x40, 0xed, 0x81, 0xd4, 0xd9, 0xcc, 0xff, 0x7e, 0xb5, 0xea, 0x2d, 0x6c, 0x62, 0x71, 0x80, 0x9e,
	0xba, 0x5a, 0xaf, 0x60, 0x27, 0x94, 0x23, 0x98, 0x1d, 0xe7, 0xbd, 0x3b, 0x47, 0x02, 0x19, 0x6f,
	0x0d, 0xa3, 0x9f, 0x01, 0xac, 0xfa, 0x89, 0xc4, 0x9b, 0x78, 0x6e, 0x0c, 0x2b, 0x78, 0xad, 0x11,
	0x8b, 0x24, 0x61, 0x39, 0x03, 0x1e, 0x61, 0x39, 0x03, 0x8e, 0x06, 0x3c, 0x87, 0xea, 0xc8, 0x10,
	0xcc, 0x13, 0x7a, 0x64, 0xee, 0x8c, 0xcb, 0x96, 0xb6, 0x2b, 0x73, 0xb2, 0xda, 0xc4, 0x82, 0x55,
	0xc6, 0xc9, 0xc2, 0x8b, 0x2b, 0x9d, 0x0c, 0xec, 0x58, 0xe7, 0xa1, 0x5c, 0xf0, 0x3c, 0xfb, 0xc0,
	0xf3, 0xcf, 0x64, 0xbe, 0xcf, 0x53, 0x5d, 0x8d, 0x65, 0x44, 0x56, 0xf2, 0xa6, 0x1f, 0xce, 0x10,
	0x87, 0xb2, 0xe6, 0x1b, 0xb4, 0xd4, 0x99, 0x0f, 0x24, 0xde, 0xc5, 0x73, 0xe9, 0x8b, 0xe8, 0x3f,
	0x31, 0xd8, 0x14, 0x6c, 0x94, 0xb8, 0x24, 0xa5, 0xe9, 0x92, 0xd0, 0x7f, 0x20, 0x2f, 0x01, 0xb1,
	0x79, 0x51, 0x0b, 0x4f, 0x2b, 0x69, 0xfd, 0x48, 0x80, 0x4e, 0xc1, 0xbb, 0xdc, 0xb4, 0x06, 0x93,
	0x75, 0x25, 0x3f, 0xd5, 0x9f, 0xfa, 0x7d, 0x02, 0x45, 0xcf, 0x8d, 0xa9, 0x24, 0xcb, 0x54, 0xa6,
	0xb1, 0x9e, 0xb7, 0x3d, 0xbb, 0xdc, 0x76, 0x75, 0x00, 0xb5, 0x4e, 0x77, 0x81, 0xd0, 0xf2, 0x87,
	0x70, 0xbe, 0x4f, 0x66, 0x79, 0x9f, 0xc3, 0x37, 0xa1, 0xec, 0xb9, 0xc7, 0x8e, 0x2a, 0x50, 0x3d,
	0xd3, 0x7a, 0xd7, 0x97, 0x7a, 0xf7, 0xb4, 0x7b, 0x72, 0xaa, 0xe9, 0xbd, 0xcb, 0x2b, 0xfd, 0xb8,
	0xdd, 0xae, 0x90, 0xc4, 0x4c, 0xfb, 0xf4, 0xbc, 0x92, 0xf9, 0x15, 0x00, 0x00, 0xff, 0xff, 0x9b,
	0xa0, 0xbc, 0x55, 0xdb, 0x0b, 0x00, 0x00,
}
