// Code generated by protoc-gen-go.
// source: IM.GeneralMessage.proto
// DO NOT EDIT!

package youmai

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type GeneralMessageType int32

const (
	GeneralMessageType_MessageType_Default GeneralMessageType = 0
	GeneralMessageType_MessageType_IM      GeneralMessageType = 1
)

var GeneralMessageType_name = map[int32]string{
	0: "MessageType_Default",
	1: "MessageType_IM",
}
var GeneralMessageType_value = map[string]int32{
	"MessageType_Default": 0,
	"MessageType_IM":      1,
}

func (x GeneralMessageType) Enum() *GeneralMessageType {
	p := new(GeneralMessageType)
	*p = x
	return p
}
func (x GeneralMessageType) String() string {
	return proto.EnumName(GeneralMessageType_name, int32(x))
}
func (x *GeneralMessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GeneralMessageType_value, data, "GeneralMessageType")
	if err != nil {
		return err
	}
	*x = GeneralMessageType(value)
	return nil
}
func (GeneralMessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor35, []int{0} }

type General_Message struct {
	UserId           *int32              `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	MessageBody      []byte              `protobuf:"bytes,2,opt,name=message_body,json=messageBody" json:"message_body,omitempty"`
	MessageType      *GeneralMessageType `protobuf:"varint,3,opt,name=message_type,json=messageType,enum=com.proto.generalmessage.GeneralMessageType" json:"message_type,omitempty"`
	MessageId        *int32              `protobuf:"varint,4,opt,name=message_id,json=messageId" json:"message_id,omitempty"`
	Length           *int32              `protobuf:"varint,5,opt,name=length" json:"length,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *General_Message) Reset()                    { *m = General_Message{} }
func (m *General_Message) String() string            { return proto.CompactTextString(m) }
func (*General_Message) ProtoMessage()               {}
func (*General_Message) Descriptor() ([]byte, []int) { return fileDescriptor35, []int{0} }

func (m *General_Message) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *General_Message) GetMessageBody() []byte {
	if m != nil {
		return m.MessageBody
	}
	return nil
}

func (m *General_Message) GetMessageType() GeneralMessageType {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return GeneralMessageType_MessageType_Default
}

func (m *General_Message) GetMessageId() int32 {
	if m != nil && m.MessageId != nil {
		return *m.MessageId
	}
	return 0
}

func (m *General_Message) GetLength() int32 {
	if m != nil && m.Length != nil {
		return *m.Length
	}
	return 0
}

type RM_General_Message struct {
	MessageId        []int32 `protobuf:"varint,1,rep,name=message_id,json=messageId" json:"message_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RM_General_Message) Reset()                    { *m = RM_General_Message{} }
func (m *RM_General_Message) String() string            { return proto.CompactTextString(m) }
func (*RM_General_Message) ProtoMessage()               {}
func (*RM_General_Message) Descriptor() ([]byte, []int) { return fileDescriptor35, []int{1} }

func (m *RM_General_Message) GetMessageId() []int32 {
	if m != nil {
		return m.MessageId
	}
	return nil
}

type Pop_General_Message struct {
	UserId           *int32              `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	MessageType      *GeneralMessageType `protobuf:"varint,2,opt,name=message_type,json=messageType,enum=com.proto.generalmessage.GeneralMessageType" json:"message_type,omitempty"`
	PopNumber        *int32              `protobuf:"varint,3,opt,name=pop_number,json=popNumber" json:"pop_number,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *Pop_General_Message) Reset()                    { *m = Pop_General_Message{} }
func (m *Pop_General_Message) String() string            { return proto.CompactTextString(m) }
func (*Pop_General_Message) ProtoMessage()               {}
func (*Pop_General_Message) Descriptor() ([]byte, []int) { return fileDescriptor35, []int{2} }

func (m *Pop_General_Message) GetUserId() int32 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *Pop_General_Message) GetMessageType() GeneralMessageType {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return GeneralMessageType_MessageType_Default
}

func (m *Pop_General_Message) GetPopNumber() int32 {
	if m != nil && m.PopNumber != nil {
		return *m.PopNumber
	}
	return 0
}

type Pop_General_Message_Ack struct {
	Messages         []*General_Message `protobuf:"bytes,1,rep,name=messages" json:"messages,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Pop_General_Message_Ack) Reset()                    { *m = Pop_General_Message_Ack{} }
func (m *Pop_General_Message_Ack) String() string            { return proto.CompactTextString(m) }
func (*Pop_General_Message_Ack) ProtoMessage()               {}
func (*Pop_General_Message_Ack) Descriptor() ([]byte, []int) { return fileDescriptor35, []int{3} }

func (m *Pop_General_Message_Ack) GetMessages() []*General_Message {
	if m != nil {
		return m.Messages
	}
	return nil
}

func init() {
	proto.RegisterType((*General_Message)(nil), "com.proto.generalmessage.General_Message")
	proto.RegisterType((*RM_General_Message)(nil), "com.proto.generalmessage.RM_General_Message")
	proto.RegisterType((*Pop_General_Message)(nil), "com.proto.generalmessage.Pop_General_Message")
	proto.RegisterType((*Pop_General_Message_Ack)(nil), "com.proto.generalmessage.Pop_General_Message_Ack")
	proto.RegisterEnum("com.proto.generalmessage.GeneralMessageType", GeneralMessageType_name, GeneralMessageType_value)
}

func init() { proto.RegisterFile("IM.GeneralMessage.proto", fileDescriptor35) }

var fileDescriptor35 = []byte{
	// 303 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0x9d, 0xd6, 0x56, 0x7b, 0x5b, 0x6a, 0xb9, 0x05, 0x3b, 0x20, 0x42, 0xcc, 0x2a, 0x8a,
	0x64, 0x51, 0x9f, 0xa0, 0xa2, 0x48, 0x16, 0x51, 0x09, 0x6e, 0x5c, 0x8d, 0x69, 0x67, 0x8c, 0xc1,
	0x24, 0x33, 0xe4, 0x67, 0x91, 0x97, 0xf1, 0xad, 0x7c, 0x1f, 0x69, 0x32, 0xad, 0x6d, 0x54, 0x74,
	0xe1, 0x6e, 0xce, 0xbd, 0x73, 0x0e, 0xdf, 0xb9, 0x70, 0xf4, 0x28, 0x0b, 0xd7, 0x0f, 0xed, 0x1b,
	0x91, 0x88, 0xd4, 0x8f, 0x5c, 0x91, 0x65, 0x7e, 0x20, 0x6c, 0x95, 0xca, 0x5c, 0x22, 0x5d, 0xc8,
	0xb8, 0x7e, 0xda, 0x41, 0xbd, 0x8f, 0xeb, 0xbd, 0xf9, 0x4e, 0xe0, 0x40, 0x5b, 0x98, 0xf6, 0xe0,
	0x04, 0xf6, 0x8a, 0x4c, 0xa4, 0x2c, 0xe4, 0x94, 0x18, 0xc4, 0xea, 0x78, 0xdd, 0xa5, 0x74, 0x38,
	0x9e, 0xc0, 0x40, 0xfb, 0xd8, 0x5c, 0xf2, 0x92, 0xb6, 0x0c, 0x62, 0x0d, 0xbc, 0xbe, 0x9e, 0x5d,
	0x4a, 0x5e, 0xe2, 0xdd, 0xe7, 0x97, 0xbc, 0x54, 0x82, 0xb6, 0x0d, 0x62, 0x0d, 0xa7, 0xe7, 0xf6,
	0x4f, 0x00, 0x0d, 0xde, 0x87, 0x52, 0x89, 0x75, 0xe0, 0x52, 0xe0, 0x31, 0xc0, 0x2a, 0x30, 0xe4,
	0x74, 0xb7, 0xe2, 0xe9, 0xe9, 0x89, 0xc3, 0xf1, 0x10, 0xba, 0x91, 0x48, 0x82, 0xfc, 0x85, 0x76,
	0x6a, 0xd4, 0x5a, 0x99, 0x17, 0x80, 0x9e, 0xcb, 0x9a, 0xcd, 0xb6, 0xc3, 0x88, 0xd1, 0xde, 0x0a,
	0x33, 0xdf, 0x08, 0x8c, 0xef, 0xa5, 0x62, 0x7f, 0x3e, 0x48, 0xb3, 0x6d, 0xeb, 0x1f, 0xda, 0x2a,
	0xa9, 0x58, 0x52, 0xc4, 0x73, 0x91, 0x56, 0xc7, 0xeb, 0x78, 0x3d, 0x25, 0xd5, 0x6d, 0x35, 0x30,
	0x9f, 0x60, 0xf2, 0x0d, 0x1f, 0x9b, 0x2d, 0x5e, 0xf1, 0x1a, 0xf6, 0x75, 0x50, 0x56, 0x15, 0xeb,
	0x4f, 0x4f, 0x7f, 0xc5, 0x58, 0x05, 0x78, 0x6b, 0xeb, 0xd9, 0x0c, 0xf0, 0x2b, 0x23, 0x4e, 0x60,
	0xbc, 0x21, 0xd9, 0x95, 0x78, 0xf6, 0x8b, 0x28, 0x1f, 0xed, 0x20, 0xc2, 0x70, 0x73, 0xe1, 0xb8,
	0x23, 0xf2, 0x11, 0x00, 0x00, 0xff, 0xff, 0x9b, 0xfc, 0x1a, 0xc4, 0x8a, 0x02, 0x00, 0x00,
}
